export const DELIVERY_EVENTS = {
  DELIVERY_ASSIGNED: "DELIVERY_ASSIGNED",
  DELIVERY_STARTED: "DELIVERY_STARTED",
  DELIVERY_COMPLETED: "DELIVERY_COMPLETED",
  DELIVERY_FAILED: "DELIVERY_FAILED",
  DELIVERY_RETURNED: "DELIVERY_RETURNED",
} as const;

export type DeliveryEventType =
  (typeof DELIVERY_EVENTS)[keyof typeof DELIVERY_EVENTS];
